gems:
  - jekyll-assets
  - jekyll-paginate
  - algoliasearch-jekyll

# Site settings
title: Nicolas Hoizey
email: nicolas@hoizey.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nicolas-hoizey.com" # the base hostname & protocol for your site
twitter_username: nhoizey
github_username:  nhoizey

# Build settings
markdown: kramdown
# Pagination
paginate: 5
paginate_path: '/page-:num/'

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - autoprefixer.yml
  - Gemfile*
  - README.md
  - LICENSE.md
  - tags/*.md
include:
  - .htaccess
  - .well-known
  - tags
# Jekyll Assets
assets:
  compress:
    css: true
    js: true

