# based on https://github.com/poole/lanyon

# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           :year/:month/:title.html
relative_permalinks: true

# Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: false
show_drafts: false
exclude: [".sass-cache", "*.sublime-project", "*.sublime-workspace", "README.md", "LICENSE.md", "node_modules", "Gruntfile.js", "package.json"]

# Setup
url:                 http://nicolas-hoizey.com
baseurl:             /
paginate:            5

# About/contact
title:               Nicolas Hoizey
tagline:             "aka @nhoizey"
description:         "Ce site est mon recueil de créations et réflexions sur des sujets très variés, de la photo au Web en passant par la société, les voyages, etc."
author:
  name:              Nicolas Hoizey
  url:               http://nicolas-hoizey.com
  email:             nicolas@hoizey.com
  twitter_username:  nhoizey
  github_username:   nhoizey

# <picture>
picture:
  source: "_assets/fullsize-images"
  output: "assets/images"
  markup: picture
  presets:
    default:
      ppi: [1, 2]
      source_1280:
        media: "(min-width: 1024px)"
        width: "1280"
      source_1024:
        media: "(min-width: 768px)"
        width: "1024"
      source_768:
        media: "(min-width: 640px)"
        width: "768"
      source_640:
        media: "(min-width: 320px)"
        width: "640"
      source_default:
        width: "320"
