markdown:    kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  footnote_backlink: "⬅︎"
  header_offset: 1

# Permalinks
permalink:           :year/:month/:title.html
relative_permalinks: true

gems:
  - jekyll-sitemap
  - jekyll-twitter-plugin
  - jekyll-archives

# Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: false
show_drafts: false
lsi: false
exclude:
  - autoprefixer.yml
  - Gemfile*
  - README.md
  - LICENSE.md
  - tags/*.md
  - Rakefile
include:
  - .htaccess
  - .well-known
  - favicon.jpg
  - tags

assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache: true

# Tags
tag_page_layout: tag
tag_page_dir: tags
tag_feed_layout: atom-tag
tag_feed_dir: tags
# tag_permalink_style: pretty

# Setup
url:                 https://nicolas-hoizey.com
baseurl:             /
paginate:            5
paginate_path:       "/page-:num/"

# About/contact
title:               Nicolas Hoizey
tagline:             "aka @nhoizey"
description:         "Ce site est mon recueil de créations et réflexions sur des sujets très variés, de la photo au Web en passant par la société, les voyages, etc."
author:
  name:              Nicolas Hoizey
  url:               https://nicolas-hoizey.com
  email:             nicolas@hoizey.com
  twitter_username:  nhoizey
  github_username:   nhoizey

# <picture>
picture:
  source: "_posts"
  posts_folders: ":year/:month/:day-:slug/"
  output: ""
  markup: picture

  presets:
    default:
      ppi: [1, 2]
      source_800:
        media: "(min-width: 800px)"
        width: "800"
      source_640:
        media: "(min-width: 640px)"
        width: "720"
      source_480:
        media: "(min-width: 480px)"
        width: "576"
      source_320:
        media: "(min-width: 320px)"
        width: "432"
      source_default:
        width: "288"
    onehalf:
      attr:
        class: "onehalf"
      ppi: [1, 2]
      source_800:
        media: "(min-width: 800px)"
        width: "432"
      source_640:
        media: "(min-width: 640px)"
        width: "360"
      source_480:
        media: "(min-width: 480px)"
        width: "288"
      source_320:
        media: "(min-width: 320px)"
        width: "216"
      source_default:
        width: "144"
    onethird:
      attr:
        class: "onethird"
      ppi: [1, 2]
      source_640:
        media: "(min-width: 640px)"
        width: "288"
      source_480:
        media: "(min-width: 480px)"
        width: "216"
      source_320:
        media: "(min-width: 320px)"
        width: "144"
      source_default:
        width: "96"
    onefourth:
      attr:
        class: "onefourth"
      ppi: [1, 2]
      source_640:
        media: "(min-width: 640px)"
        width: "216"
      source_480:
        media: "(min-width: 480px)"
        width: "144"
      source_320:
        media: "(min-width: 320px)"
        width: "144"
      source_default:
        width: "96"

jekyll-archives:
  enabled:
    - year
    - month
  layouts:
    year: archives-year
    month: archives-month
  permalinks:
    year: /:year/
    month: /:year/:month/

twitter:
  consumer_key: …
  consumer_secret: …
  access_token: …
  access_token_secret: …

youtube:
  api_key: …

algolia:
  application_id: …
  index_name: …
  search_only_api_key: …
