gems:
  - jekyll-assets
  - jekyll-paginate
  - algoliasearch-jekyll
  - jekyll-post-files

# Site settings
title: Nicolas Hoizey
email: nicolas@hoizey.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nicolas-hoizey.com" # the base hostname & protocol for your site
twitter_username: nhoizey
github_username:  nhoizey

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  footnote_backlink: "⬆︎"
  header_offset: 1

# Pagination
paginate: 5
paginate_path: '/page-:num/'

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Tags
tag_page_layout: tag
tag_page_dir: tags
tag_feed_layout: atom-tag
tag_feed_dir: tags

exclude:
  - autoprefixer.yml
  - Gemfile*
  - README.md
  - LICENSE.md
  - tags/*.md
  - Rakefile
include:
  - .htaccess
  - .well-known
  - favicon.jpg
  - tags

# Jekyll Assets
assets:
  compress:
    css: true
    js: true

# Algolia
algolia:
  application_id: '1YLVA0N7BR'
  index_name: 'blog_posts'
  read_only_api_key: '3b98a9f7c736ecc42aac5d52140beb41'
  excluded_files:
    - 404.html
    - index.html
