markdown:            kramdown
highlighter:         pygments

# Permalinks
permalink:           :year/:month/:title.html
relative_permalinks: true

gems:
  - jekyll-sitemap
  - jekyll-twitter-plugin
  - jekyll-archives

# Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: false
show_drafts: false
lsi: false
exclude:
  - autoprefixer.yml
  - "Gemfile*"
  - README.md
  - LICENSE.md
  - Rakefile
  - "*.sublime*"
  - Rakefile
  - "*.jpg"
  - "*.png"
  - "*.gif"
include:
  - .htaccess
  - favicon.jpg

assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache: true

# Tags
tag_page_layout: tag
tag_page_dir: tags
tag_feed_layout: atom-tag
tag_feed_dir: tags
# tag_permalink_style: pretty

# Setup
url:                 http://nicolas-hoizey.com
baseurl:             /
paginate:            5
paginate_path:       "/:num/"

# About/contact
title:               Nicolas Hoizey
tagline:             "aka @nhoizey"
description:         "Ce site est mon recueil de créations et réflexions sur des sujets très variés, de la photo au Web en passant par la société, les voyages, etc."
author:
  name:              Nicolas Hoizey
  url:               http://nicolas-hoizey.com
  email:             nicolas@hoizey.com
  twitter_username:  nhoizey
  github_username:   nhoizey

# <picture>
picture:
  source: "_posts"
  posts_folders: ":year/:month/:day-:slug/"
  output: ""
  markup: picture

  presets:
    default:
      ppi: [1, 2]
      source_640:
        media: "(min-width: 580px)"
        width: "640"
      source_530:
        media: "(min-width: 470px)"
        width: "530"
      source_420:
        media: "(min-width: 350px)"
        width: "430"
      source_default:
        width: "320"

jekyll-archives:
  enabled:
    - "year"
    - "month"
  layouts:
    year: "archives-year"
    month: "archives-month"
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"

twitter:
  consumer_key: …
  consumer_secret: …
  access_token: …
  access_token_secret: …

youtube:
  api_key: …

algolia:
  application_id: …
  index_name: …
  search_only_api_key: …
