gems:
  - jekyll-assets
  - jekyll-paginate
  - algoliasearch-jekyll
  - jekyll-postfiles
  - jekyll-cloudinary

# Site settings
title: Nicolas Hoizey
email: nicolas@hoizey.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://nicolas-hoizey.com"
twitter_username: nhoizey
github_username:  nhoizey

# Permalinks
permalink: :year/:month/:title.html

# Markdown parsing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  footnote_backlink: "⬆︎"
  header_offset: 1

# Pagination
paginate: 5
paginate_path: /page-:num/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      lang: fr

# Tags
tag_page_layout: tag
tag_page_dir: tags
tag_feed_layout: atom-tag
tag_feed_dir: tags

exclude:
  - autoprefixer.yml
  - Gemfile*
  - README.md
  - LICENSE.md
  - tags/*.md
  - Rakefile
include:
  - .htaccess
  - .well-known
  - favicon.jpg
  - tags

# Jekyll Assets
assets:
  compress:
    css: true
    js: true
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

# Algolia
algolia:
  application_id: …
  index_name: …
  read_only_api_key: …
  record_css_selector: 'p,li,figure,tr,div'
  excluded_files:
    - 404.html
    - index.html

youtube:
  api_key: …

# Cloudinary
cloudinary:
  cloud_name: nho
  verbose: false
  presets:
    default:
      min_width: 360
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    onehalf:
      min_width: 180
      max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 25rem, 45vw'
      figure: always
      attributes:
        class: onehalf
    onethird:
      min_width: 120
      max_width: 560
      steps: 5
      sizes: '(min-width: 50rem) 17rem, 30vw'
      figure: always
      attributes:
        class: onethird right
    onefourth:
      min_width: 100
      max_width: 400
      steps: 5
      sizes: '(min-width: 50rem) 13rem, 23vw'
      figure: always
      attributes:
        class: onefourth right
    logo:
      min_width: 100
      max_width: 400
      steps: 3
      sizes: '(min-width: 50rem) 13rem, (min-width: 40rem) 25vw, 45vw'
      figure: never
      attributes:
        class: logo

jekyll-archives:
  enabled:
    - year
    - month
  layouts:
    year: archives-year
    month: archives-month
  permalinks:
    year: /:year/
    month: /:year/:month/
